#!/bin/bash

# Script to install mkcert's local CA for trusted certificates
# This will eliminate browser security warnings

echo "🔐 Installing mkcert Local CA..."
echo ""
echo "This will install mkcert's root certificate into your system's trust store."
echo "You will be prompted for your Mac password."
echo ""

# Check if mkcert is installed
if ! command -v mkcert &> /dev/null; then
    echo "❌ mkcert is not installed."
    echo "Install it with: brew install mkcert"
    exit 1
fi

# Install the local CA
mkcert -install

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Local CA installed successfully!"
    echo ""
    echo "Your browser will now trust certificates generated by mkcert."
    echo "Restart your browser if it's already open."
    echo ""
    echo "The server should now work without security warnings at:"
    echo "  https://localhost:3000"
else
    echo ""
    echo "⚠️  CA installation failed or was cancelled."
    echo "You can still use the certificates, but browsers may show warnings."
fi

