#!/bin/bash

# EmailJS Setup Helper Script
# This script helps you set up EmailJS for real email sending

echo "🚀 EmailJS Setup Helper"
echo "========================"
echo ""
echo "This script will help you configure EmailJS for real email sending."
echo ""
echo "📋 Prerequisites:"
echo "   1. EmailJS account (sign up at https://www.emailjs.com/)"
echo "   2. Service ID (from Email Services)"
echo "   3. Template ID (from Email Templates)"
echo "   4. Public Key (from Account -> General)"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/n): " overwrite
    if [ "$overwrite" != "y" ]; then
        echo "❌ Setup cancelled. Existing .env file preserved."
        exit 0
    fi
fi

echo ""
echo "Please enter your EmailJS credentials:"
echo ""

read -p "Service ID (starts with 'service_'): " SERVICE_ID
read -p "Template ID (starts with 'template_'): " TEMPLATE_ID
read -p "Public Key: " PUBLIC_KEY

# Validate inputs
if [ -z "$SERVICE_ID" ] || [ -z "$TEMPLATE_ID" ] || [ -z "$PUBLIC_KEY" ]; then
    echo "❌ Error: All fields are required!"
    exit 1
fi

# Create .env file
cat > .env << EOF
# EmailJS Configuration
# Generated by setup-email.sh on $(date)

VITE_EMAILJS_SERVICE_ID=$SERVICE_ID
VITE_EMAILJS_TEMPLATE_ID=$TEMPLATE_ID
VITE_EMAILJS_PUBLIC_KEY=$PUBLIC_KEY
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "📝 Configuration saved:"
echo "   Service ID: $SERVICE_ID"
echo "   Template ID: $TEMPLATE_ID"
echo "   Public Key: ${PUBLIC_KEY:0:10}..."
echo ""
echo "⚠️  IMPORTANT: Restart your development server for changes to take effect!"
echo ""
echo "   Run: npm run dev"
echo ""
echo "🧪 Test it:"
echo "   1. Open https://localhost:3000/"
echo "   2. Use chatbot: 'Send sales report to your-email@example.com as PDF'"
echo "   3. Check your inbox!"
echo ""

